/* Auto-generated by Admin Panel */

const DEFAULT_DATA = {
  "name": "Tanim",
  "heroLabel": "Materials Science & Engineering",
  "subtitle": "B.Sc. Student at RUET · Passionate about advanced materials, nanotechnology & sustainable engineering",
  "typewriterWords": [
    "Materials Engineer",
    "Problem Solver",
    "RUET Student"
  ],
  "photoURL": "https://res.cloudinary.com/dr2b6pzux/image/upload/v1776824006/jwgta6utmxkamluc5piz.png",
  "cvLink": "#"
};

function getData() {
  try {
    const saved = localStorage.getItem('portfolioData');
    if (saved) { const parsed = JSON.parse(saved); return deepMerge(DEFAULT_DATA, parsed); }
  } catch (e) {}
  return JSON.parse(JSON.stringify(DEFAULT_DATA));
}

function saveData(data) {
  try { localStorage.setItem('portfolioData', JSON.stringify(data)); return true; } catch(e) { return false; }
}

function resetData() {
  localStorage.removeItem('portfolioData');
  return JSON.parse(JSON.stringify(DEFAULT_DATA));
}

function deepMerge(target, source) {
  const result = Object.assign({}, target);
  for (const key of Object.keys(source)) {
    if (source[key] !== null && typeof source[key] === 'object' && !Array.isArray(source[key])) {
      result[key] = deepMerge(target[key] || {}, source[key]);
    } else { result[key] = source[key]; }
  }
  return result;
}
