backend:
  name: github
  repo: tanim-mse/portfolio_tanim
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "_data/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "text" }
      - { label: "Tags (comma separated)", name: "tags", widget: "string" }
      - { label: "Project Link", name: "link", widget: "string", required: false }

  - name: "skills"
    label: "Skills"
    folder: "_data/skills"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Category Title", name: "title", widget: "string" }
      - label: "Skills List"
        name: "items"
        widget: "list"
        field: { label: "Skill", name: "skill", widget: "string" }

  - name: "research"
    label: "Research Interests"
    folder: "_data/research"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Research Interest", name: "title", widget: "string" }

  - name: "publications"
    label: "Publications"
    folder: "_data/publications"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Details", name: "details", widget: "text", required: false }
